baseURL = "https://www.junghacker.de"
languageCode = "de-de"
title = "Junghacker - Programmieren für Kids"
theme = "devfest"
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "jungH4X0r.github.io"


enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true


[markup.goldmark.renderer]
unsafe= true
=======
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
    title = "junghacker"
    date = "2019-07-13"
    description = "Du willst gerne deine eigenen Computerspiele entwickeln, mit Elektronik basteln und löten, kleine Roboter programmieren oder auch mit freier Software Medien produzieren und gestalten? Dann bist du bei uns genau richtig!"
    images = ["/images/logo_transparent.png"]
    email = "info@junghacker.de"
    keywords = "programming, kids, halle, eigenbaukombinat, junghacker"
    copyright = "We :heart:️ programming"
    cfpUrl = "https://cfp.chaoszone.cz/"
    subscriptionUrl = "https://tickets.eigenbaukombinat.de/ebk/"
    appleTouchIcon = "/images/apple-touch-icon.png"
    favicon32 = "/images/favicon-32x32.png"
    favicon16 = "/images/favicon-16x16.png"
    manifest = "/images/manifest.json"
    safariPinnedTab = "/images/apple-touch-icon.png"
    themeColor = "#673ab7"

[params.logos]
    jumbo = "/images/logos/logo_transparent.png"
    header = "/images/logos/logo_transparent.png"
    footer = "/images/logos/logo_transparent_grey.png"

#[languages]
#[languages.en]
#    weight = 1
#    languageName = "gb"#

[taxonomies]
  tag = "tags"

